# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xcon_imperial.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_XCon_Imperial(object):
    def setupUi(self, XCon_Imperial):
        XCon_Imperial.setObjectName("XCon_Imperial")
        XCon_Imperial.resize(1647, 898)
        self.centralWidget = QtWidgets.QWidget(XCon_Imperial)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 3, 8, 1, 1)
        self.verticalLayout_nu_laser_blue_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_nu_laser_blue_1.setSpacing(6)
        self.verticalLayout_nu_laser_blue_1.setObjectName("verticalLayout_nu_laser_blue_1")
        self.gridLayout_2.addLayout(self.verticalLayout_nu_laser_blue_1, 3, 0, 3, 8)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 7, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 9, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 6, 0, 1, 8)
        spacerItem5 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 3, 1, 1)
        self.doubleSpinBox_nu_blue_1_want = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_nu_blue_1_want.setFont(font)
        self.doubleSpinBox_nu_blue_1_want.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_nu_blue_1_want.setDecimals(6)
        self.doubleSpinBox_nu_blue_1_want.setMinimum(755.0)
        self.doubleSpinBox_nu_blue_1_want.setMaximum(755.5)
        self.doubleSpinBox_nu_blue_1_want.setSingleStep(1e-06)
        self.doubleSpinBox_nu_blue_1_want.setProperty("value", 755.18682)
        self.doubleSpinBox_nu_blue_1_want.setObjectName("doubleSpinBox_nu_blue_1_want")
        self.gridLayout_2.addWidget(self.doubleSpinBox_nu_blue_1_want, 7, 4, 1, 4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 7, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 0, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 8, 0, 1, 8)
        spacerItem10 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 5, 8, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 4, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 4, 8, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 0, 5, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 0, 6, 1, 1)
        self.pushButton_lock_laser_blue_1_on = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_lock_laser_blue_1_on.setFont(font)
        self.pushButton_lock_laser_blue_1_on.setObjectName("pushButton_lock_laser_blue_1_on")
        self.gridLayout_2.addWidget(self.pushButton_lock_laser_blue_1_on, 10, 0, 1, 4)
        self.pushButton_lock_laser_blue_1_off = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_lock_laser_blue_1_off.setFont(font)
        self.pushButton_lock_laser_blue_1_off.setObjectName("pushButton_lock_laser_blue_1_off")
        self.gridLayout_2.addWidget(self.pushButton_lock_laser_blue_1_off, 10, 4, 1, 4)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 4, 1, 2)
        self.pushButton_smooth_change_laser_blue_1_start = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_smooth_change_laser_blue_1_start.setFont(font)
        self.pushButton_smooth_change_laser_blue_1_start.setObjectName("pushButton_smooth_change_laser_blue_1_start")
        self.gridLayout_2.addWidget(self.pushButton_smooth_change_laser_blue_1_start, 14, 0, 1, 4)
        self.doubleSpinBox_nu_blue_1_smooth_want = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_nu_blue_1_smooth_want.setFont(font)
        self.doubleSpinBox_nu_blue_1_smooth_want.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_nu_blue_1_smooth_want.setDecimals(6)
        self.doubleSpinBox_nu_blue_1_smooth_want.setMinimum(755.0)
        self.doubleSpinBox_nu_blue_1_smooth_want.setMaximum(755.5)
        self.doubleSpinBox_nu_blue_1_smooth_want.setProperty("value", 755.18684)
        self.doubleSpinBox_nu_blue_1_smooth_want.setObjectName("doubleSpinBox_nu_blue_1_smooth_want")
        self.gridLayout_2.addWidget(self.doubleSpinBox_nu_blue_1_smooth_want, 12, 4, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 12, 0, 1, 4)
        self.pushButton_smooth_change_laser_blue_1_stop = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_smooth_change_laser_blue_1_stop.setFont(font)
        self.pushButton_smooth_change_laser_blue_1_stop.setObjectName("pushButton_smooth_change_laser_blue_1_stop")
        self.gridLayout_2.addWidget(self.pushButton_smooth_change_laser_blue_1_stop, 14, 4, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 13, 0, 1, 4)
        self.doubleSpinBox_nu_blue_1_smooth_delta_t = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_nu_blue_1_smooth_delta_t.setFont(font)
        self.doubleSpinBox_nu_blue_1_smooth_delta_t.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_nu_blue_1_smooth_delta_t.setDecimals(1)
        self.doubleSpinBox_nu_blue_1_smooth_delta_t.setMaximum(300.0)
        self.doubleSpinBox_nu_blue_1_smooth_delta_t.setSingleStep(0.1)
        self.doubleSpinBox_nu_blue_1_smooth_delta_t.setProperty("value", 10.0)
        self.doubleSpinBox_nu_blue_1_smooth_delta_t.setObjectName("doubleSpinBox_nu_blue_1_smooth_delta_t")
        self.gridLayout_2.addWidget(self.doubleSpinBox_nu_blue_1_smooth_delta_t, 13, 4, 1, 4)
        self.doubleSpinBox_lock_blue_1_alpha = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_lock_blue_1_alpha.setFont(font)
        self.doubleSpinBox_lock_blue_1_alpha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_lock_blue_1_alpha.setDecimals(2)
        self.doubleSpinBox_lock_blue_1_alpha.setMaximum(999999.0)
        self.doubleSpinBox_lock_blue_1_alpha.setSingleStep(0.05)
        self.doubleSpinBox_lock_blue_1_alpha.setProperty("value", 20.0)
        self.doubleSpinBox_lock_blue_1_alpha.setObjectName("doubleSpinBox_lock_blue_1_alpha")
        self.gridLayout_2.addWidget(self.doubleSpinBox_lock_blue_1_alpha, 9, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 11, 0, 1, 8)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 9, 4, 1, 3)
        self.label_nu_blue_1_is = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_nu_blue_1_is.setFont(font)
        self.label_nu_blue_1_is.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nu_blue_1_is.setObjectName("label_nu_blue_1_is")
        self.gridLayout_2.addWidget(self.label_nu_blue_1_is, 1, 6, 1, 2)
        self.doubleSpinBox_lock_blue_1_beta = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_lock_blue_1_beta.setFont(font)
        self.doubleSpinBox_lock_blue_1_beta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_lock_blue_1_beta.setDecimals(2)
        self.doubleSpinBox_lock_blue_1_beta.setMaximum(999999.0)
        self.doubleSpinBox_lock_blue_1_beta.setSingleStep(0.01)
        self.doubleSpinBox_lock_blue_1_beta.setProperty("value", 0.0)
        self.doubleSpinBox_lock_blue_1_beta.setObjectName("doubleSpinBox_lock_blue_1_beta")
        self.gridLayout_2.addWidget(self.doubleSpinBox_lock_blue_1_beta, 9, 7, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 2, 0, 1, 8)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 2)
        self.label_lock_blue_1_status = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_lock_blue_1_status.setFont(font)
        self.label_lock_blue_1_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lock_blue_1_status.setObjectName("label_lock_blue_1_status")
        self.gridLayout_2.addWidget(self.label_lock_blue_1_status, 1, 2, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.doubleSpinBox_nu_red_2_want = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_nu_red_2_want.setFont(font)
        self.doubleSpinBox_nu_red_2_want.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_nu_red_2_want.setDecimals(6)
        self.doubleSpinBox_nu_red_2_want.setMinimum(350.0)
        self.doubleSpinBox_nu_red_2_want.setMaximum(351.0)
        self.doubleSpinBox_nu_red_2_want.setSingleStep(1e-06)
        self.doubleSpinBox_nu_red_2_want.setProperty("value", 350.8626)
        self.doubleSpinBox_nu_red_2_want.setObjectName("doubleSpinBox_nu_red_2_want")
        self.gridLayout_5.addWidget(self.doubleSpinBox_nu_red_2_want, 6, 5, 1, 4)
        self.pushButton_smooth_change_laser_red_2_stop = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_smooth_change_laser_red_2_stop.setFont(font)
        self.pushButton_smooth_change_laser_red_2_stop.setObjectName("pushButton_smooth_change_laser_red_2_stop")
        self.gridLayout_5.addWidget(self.pushButton_smooth_change_laser_red_2_stop, 13, 5, 1, 4)
        spacerItem15 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem15, 3, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 12, 1, 1, 4)
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 8, 1, 1, 3)
        self.pushButton_smooth_change_laser_red_2_start = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_smooth_change_laser_red_2_start.setFont(font)
        self.pushButton_smooth_change_laser_red_2_start.setObjectName("pushButton_smooth_change_laser_red_2_start")
        self.gridLayout_5.addWidget(self.pushButton_smooth_change_laser_red_2_start, 13, 1, 1, 4)
        self.pushButton_lock_laser_red_2_on = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_lock_laser_red_2_on.setFont(font)
        self.pushButton_lock_laser_red_2_on.setObjectName("pushButton_lock_laser_red_2_on")
        self.gridLayout_5.addWidget(self.pushButton_lock_laser_red_2_on, 9, 1, 1, 4)
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 11, 1, 1, 4)
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 8, 5, 1, 3)
        self.pushButton_lock_laser_red_2_off = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_lock_laser_red_2_off.setFont(font)
        self.pushButton_lock_laser_red_2_off.setObjectName("pushButton_lock_laser_red_2_off")
        self.gridLayout_5.addWidget(self.pushButton_lock_laser_red_2_off, 9, 5, 1, 4)
        spacerItem16 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem16, 0, 7, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem17, 0, 5, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem18, 0, 8, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem19, 0, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem20, 0, 4, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem21, 0, 3, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem22, 0, 2, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem23, 0, 6, 1, 1)
        self.doubleSpinBox_lock_red_2_alpha = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_lock_red_2_alpha.setFont(font)
        self.doubleSpinBox_lock_red_2_alpha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_lock_red_2_alpha.setDecimals(2)
        self.doubleSpinBox_lock_red_2_alpha.setMaximum(999999.0)
        self.doubleSpinBox_lock_red_2_alpha.setSingleStep(0.05)
        self.doubleSpinBox_lock_red_2_alpha.setProperty("value", 20.0)
        self.doubleSpinBox_lock_red_2_alpha.setObjectName("doubleSpinBox_lock_red_2_alpha")
        self.gridLayout_5.addWidget(self.doubleSpinBox_lock_red_2_alpha, 8, 4, 1, 1)
        self.doubleSpinBox_lock_red_2_beta = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_lock_red_2_beta.setFont(font)
        self.doubleSpinBox_lock_red_2_beta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_lock_red_2_beta.setMaximum(100.0)
        self.doubleSpinBox_lock_red_2_beta.setSingleStep(0.01)
        self.doubleSpinBox_lock_red_2_beta.setObjectName("doubleSpinBox_lock_red_2_beta")
        self.gridLayout_5.addWidget(self.doubleSpinBox_lock_red_2_beta, 8, 8, 1, 1)
        self.doubleSpinBox_nu_red_2_smooth_want = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_nu_red_2_smooth_want.setFont(font)
        self.doubleSpinBox_nu_red_2_smooth_want.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_nu_red_2_smooth_want.setDecimals(6)
        self.doubleSpinBox_nu_red_2_smooth_want.setMinimum(350.0)
        self.doubleSpinBox_nu_red_2_smooth_want.setMaximum(351.0)
        self.doubleSpinBox_nu_red_2_smooth_want.setSingleStep(1e-06)
        self.doubleSpinBox_nu_red_2_smooth_want.setProperty("value", 350.86239)
        self.doubleSpinBox_nu_red_2_smooth_want.setObjectName("doubleSpinBox_nu_red_2_smooth_want")
        self.gridLayout_5.addWidget(self.doubleSpinBox_nu_red_2_smooth_want, 11, 5, 1, 4)
        self.doubleSpinBox_nu_red_2_smooth_delta_t = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_nu_red_2_smooth_delta_t.setFont(font)
        self.doubleSpinBox_nu_red_2_smooth_delta_t.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_nu_red_2_smooth_delta_t.setDecimals(1)
        self.doubleSpinBox_nu_red_2_smooth_delta_t.setMaximum(300.0)
        self.doubleSpinBox_nu_red_2_smooth_delta_t.setSingleStep(0.1)
        self.doubleSpinBox_nu_red_2_smooth_delta_t.setProperty("value", 10.0)
        self.doubleSpinBox_nu_red_2_smooth_delta_t.setObjectName("doubleSpinBox_nu_red_2_smooth_delta_t")
        self.gridLayout_5.addWidget(self.doubleSpinBox_nu_red_2_smooth_delta_t, 12, 5, 1, 4)
        self.line_13 = QtWidgets.QFrame(self.groupBox_4)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_5.addWidget(self.line_13, 7, 1, 1, 8)
        self.verticalLayout_nu_laser_red_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_nu_laser_red_2.setSpacing(6)
        self.verticalLayout_nu_laser_red_2.setObjectName("verticalLayout_nu_laser_red_2")
        self.gridLayout_5.addLayout(self.verticalLayout_nu_laser_red_2, 3, 1, 3, 8)
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 6, 1, 1, 4)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 1, 5, 1, 2)
        spacerItem24 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem24, 5, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 1, 1, 1, 2)
        spacerItem25 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem25, 4, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.groupBox_4)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_5.addWidget(self.line_12, 10, 1, 1, 8)
        self.label_nu_red_2_is = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_nu_red_2_is.setFont(font)
        self.label_nu_red_2_is.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nu_red_2_is.setObjectName("label_nu_red_2_is")
        self.gridLayout_5.addWidget(self.label_nu_red_2_is, 1, 7, 1, 2)
        self.label_lock_red_2_status = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_lock_red_2_status.setFont(font)
        self.label_lock_red_2_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lock_red_2_status.setObjectName("label_lock_red_2_status")
        self.gridLayout_5.addWidget(self.label_lock_red_2_status, 1, 3, 1, 2)
        self.line_14 = QtWidgets.QFrame(self.groupBox_4)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_5.addWidget(self.line_14, 2, 1, 1, 8)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.gridLayout.addWidget(self.groupBox_4, 2, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_lock_laser_blue_2_on = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_lock_laser_blue_2_on.setFont(font)
        self.pushButton_lock_laser_blue_2_on.setObjectName("pushButton_lock_laser_blue_2_on")
        self.gridLayout_3.addWidget(self.pushButton_lock_laser_blue_2_on, 10, 1, 1, 4)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 9, 5, 1, 3)
        self.doubleSpinBox_nu_blue_2_smooth_want = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_nu_blue_2_smooth_want.setFont(font)
        self.doubleSpinBox_nu_blue_2_smooth_want.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_nu_blue_2_smooth_want.setDecimals(6)
        self.doubleSpinBox_nu_blue_2_smooth_want.setMinimum(755.0)
        self.doubleSpinBox_nu_blue_2_smooth_want.setMaximum(755.5)
        self.doubleSpinBox_nu_blue_2_smooth_want.setSingleStep(1e-06)
        self.doubleSpinBox_nu_blue_2_smooth_want.setProperty("value", 755.25816)
        self.doubleSpinBox_nu_blue_2_smooth_want.setObjectName("doubleSpinBox_nu_blue_2_smooth_want")
        self.gridLayout_3.addWidget(self.doubleSpinBox_nu_blue_2_smooth_want, 12, 5, 1, 4)
        self.verticalLayout_nu_laser_blue_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_nu_laser_blue_2.setSpacing(6)
        self.verticalLayout_nu_laser_blue_2.setObjectName("verticalLayout_nu_laser_blue_2")
        self.gridLayout_3.addLayout(self.verticalLayout_nu_laser_blue_2, 3, 1, 3, 8)
        self.doubleSpinBox_lock_blue_2_alpha = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_lock_blue_2_alpha.setFont(font)
        self.doubleSpinBox_lock_blue_2_alpha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_lock_blue_2_alpha.setMaximum(999999.0)
        self.doubleSpinBox_lock_blue_2_alpha.setSingleStep(0.05)
        self.doubleSpinBox_lock_blue_2_alpha.setProperty("value", 20.0)
        self.doubleSpinBox_lock_blue_2_alpha.setObjectName("doubleSpinBox_lock_blue_2_alpha")
        self.gridLayout_3.addWidget(self.doubleSpinBox_lock_blue_2_alpha, 9, 4, 1, 1)
        self.doubleSpinBox_lock_blue_2_beta = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_lock_blue_2_beta.setFont(font)
        self.doubleSpinBox_lock_blue_2_beta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_lock_blue_2_beta.setMaximum(999999.0)
        self.doubleSpinBox_lock_blue_2_beta.setSingleStep(0.01)
        self.doubleSpinBox_lock_blue_2_beta.setProperty("value", 0.0)
        self.doubleSpinBox_lock_blue_2_beta.setObjectName("doubleSpinBox_lock_blue_2_beta")
        self.gridLayout_3.addWidget(self.doubleSpinBox_lock_blue_2_beta, 9, 8, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.groupBox_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_3.addWidget(self.line_7, 8, 1, 1, 8)
        self.line_5 = QtWidgets.QFrame(self.groupBox_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 2, 1, 1, 8)
        self.doubleSpinBox_nu_blue_2_want = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_nu_blue_2_want.setFont(font)
        self.doubleSpinBox_nu_blue_2_want.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_nu_blue_2_want.setDecimals(6)
        self.doubleSpinBox_nu_blue_2_want.setMinimum(755.0)
        self.doubleSpinBox_nu_blue_2_want.setMaximum(755.5)
        self.doubleSpinBox_nu_blue_2_want.setSingleStep(1e-06)
        self.doubleSpinBox_nu_blue_2_want.setProperty("value", 755.25814)
        self.doubleSpinBox_nu_blue_2_want.setObjectName("doubleSpinBox_nu_blue_2_want")
        self.gridLayout_3.addWidget(self.doubleSpinBox_nu_blue_2_want, 7, 5, 1, 4)
        self.doubleSpinBox_nu_blue_2_smooth_delta_t = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_nu_blue_2_smooth_delta_t.setFont(font)
        self.doubleSpinBox_nu_blue_2_smooth_delta_t.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_nu_blue_2_smooth_delta_t.setDecimals(1)
        self.doubleSpinBox_nu_blue_2_smooth_delta_t.setMaximum(300.0)
        self.doubleSpinBox_nu_blue_2_smooth_delta_t.setSingleStep(0.1)
        self.doubleSpinBox_nu_blue_2_smooth_delta_t.setProperty("value", 10.0)
        self.doubleSpinBox_nu_blue_2_smooth_delta_t.setObjectName("doubleSpinBox_nu_blue_2_smooth_delta_t")
        self.gridLayout_3.addWidget(self.doubleSpinBox_nu_blue_2_smooth_delta_t, 13, 5, 1, 4)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 7, 1, 1, 4)
        self.pushButton_smooth_change_laser_blue_2_start = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_smooth_change_laser_blue_2_start.setFont(font)
        self.pushButton_smooth_change_laser_blue_2_start.setObjectName("pushButton_smooth_change_laser_blue_2_start")
        self.gridLayout_3.addWidget(self.pushButton_smooth_change_laser_blue_2_start, 14, 1, 1, 4)
        spacerItem26 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem26, 0, 4, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem27, 0, 3, 1, 1)
        self.label_lock_blue_2_status = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_lock_blue_2_status.setFont(font)
        self.label_lock_blue_2_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lock_blue_2_status.setObjectName("label_lock_blue_2_status")
        self.gridLayout_3.addWidget(self.label_lock_blue_2_status, 1, 3, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 5, 1, 2)
        self.pushButton_smooth_change_laser_blue_2_stop = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_smooth_change_laser_blue_2_stop.setFont(font)
        self.pushButton_smooth_change_laser_blue_2_stop.setObjectName("pushButton_smooth_change_laser_blue_2_stop")
        self.gridLayout_3.addWidget(self.pushButton_smooth_change_laser_blue_2_stop, 14, 5, 1, 4)
        self.line_6 = QtWidgets.QFrame(self.groupBox_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 6, 1, 1, 8)
        spacerItem28 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem28, 0, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem29, 0, 7, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem30, 0, 8, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem31, 0, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 9, 1, 1, 3)
        self.label_nu_blue_2_is = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_nu_blue_2_is.setFont(font)
        self.label_nu_blue_2_is.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nu_blue_2_is.setObjectName("label_nu_blue_2_is")
        self.gridLayout_3.addWidget(self.label_nu_blue_2_is, 1, 7, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 13, 1, 1, 4)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 12, 1, 1, 4)
        spacerItem32 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem32, 5, 0, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem33, 4, 0, 1, 1)
        self.pushButton_lock_laser_blue_2_off = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_lock_laser_blue_2_off.setFont(font)
        self.pushButton_lock_laser_blue_2_off.setObjectName("pushButton_lock_laser_blue_2_off")
        self.gridLayout_3.addWidget(self.pushButton_lock_laser_blue_2_off, 10, 5, 1, 4)
        spacerItem34 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem34, 0, 6, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem35, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 1, 1, 2)
        spacerItem36 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem36, 0, 2, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.groupBox_2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_3.addWidget(self.line_8, 11, 1, 1, 8)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.groupBox_2, 1, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 11, 0, 1, 4)
        spacerItem37 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem37, 0, 4, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem38, 0, 7, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem39, 0, 5, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem40, 0, 6, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.groupBox_3)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_4.addWidget(self.line_10, 7, 0, 1, 8)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 2)
        spacerItem41 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem41, 5, 8, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 6, 0, 1, 4)
        spacerItem42 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem42, 0, 0, 1, 1)
        self.pushButton_lock_laser_red_1_on = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_lock_laser_red_1_on.setFont(font)
        self.pushButton_lock_laser_red_1_on.setObjectName("pushButton_lock_laser_red_1_on")
        self.gridLayout_4.addWidget(self.pushButton_lock_laser_red_1_on, 9, 0, 1, 4)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 8, 0, 1, 3)
        spacerItem43 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem43, 0, 2, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem44, 0, 1, 1, 1)
        self.verticalLayout_nu_laser_red_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_nu_laser_red_1.setSpacing(6)
        self.verticalLayout_nu_laser_red_1.setObjectName("verticalLayout_nu_laser_red_1")
        self.gridLayout_4.addLayout(self.verticalLayout_nu_laser_red_1, 3, 0, 3, 8)
        spacerItem45 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem45, 4, 8, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 12, 0, 1, 4)
        spacerItem46 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem46, 3, 8, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem47, 0, 3, 1, 1)
        self.doubleSpinBox_nu_red_1_smooth_want = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_nu_red_1_smooth_want.setFont(font)
        self.doubleSpinBox_nu_red_1_smooth_want.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_nu_red_1_smooth_want.setDecimals(6)
        self.doubleSpinBox_nu_red_1_smooth_want.setMinimum(345.5)
        self.doubleSpinBox_nu_red_1_smooth_want.setMaximum(346.5)
        self.doubleSpinBox_nu_red_1_smooth_want.setSingleStep(1e-06)
        self.doubleSpinBox_nu_red_1_smooth_want.setProperty("value", 346.00005)
        self.doubleSpinBox_nu_red_1_smooth_want.setObjectName("doubleSpinBox_nu_red_1_smooth_want")
        self.gridLayout_4.addWidget(self.doubleSpinBox_nu_red_1_smooth_want, 11, 4, 1, 4)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 4, 1, 2)
        self.label_nu_red_1_is = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_nu_red_1_is.setFont(font)
        self.label_nu_red_1_is.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nu_red_1_is.setObjectName("label_nu_red_1_is")
        self.gridLayout_4.addWidget(self.label_nu_red_1_is, 1, 6, 1, 2)
        self.line_9 = QtWidgets.QFrame(self.groupBox_3)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_4.addWidget(self.line_9, 2, 0, 1, 8)
        self.label_lock_red_1_status = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_lock_red_1_status.setFont(font)
        self.label_lock_red_1_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lock_red_1_status.setObjectName("label_lock_red_1_status")
        self.gridLayout_4.addWidget(self.label_lock_red_1_status, 1, 2, 1, 2)
        self.pushButton_smooth_change_laser_red_1_start = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_smooth_change_laser_red_1_start.setFont(font)
        self.pushButton_smooth_change_laser_red_1_start.setObjectName("pushButton_smooth_change_laser_red_1_start")
        self.gridLayout_4.addWidget(self.pushButton_smooth_change_laser_red_1_start, 13, 0, 1, 4)
        self.doubleSpinBox_lock_red_1_alpha = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_lock_red_1_alpha.setFont(font)
        self.doubleSpinBox_lock_red_1_alpha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_lock_red_1_alpha.setMaximum(999999.0)
        self.doubleSpinBox_lock_red_1_alpha.setSingleStep(0.05)
        self.doubleSpinBox_lock_red_1_alpha.setProperty("value", 20.0)
        self.doubleSpinBox_lock_red_1_alpha.setObjectName("doubleSpinBox_lock_red_1_alpha")
        self.gridLayout_4.addWidget(self.doubleSpinBox_lock_red_1_alpha, 8, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 8, 4, 1, 3)
        self.pushButton_smooth_change_laser_red_1_stop = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_smooth_change_laser_red_1_stop.setFont(font)
        self.pushButton_smooth_change_laser_red_1_stop.setObjectName("pushButton_smooth_change_laser_red_1_stop")
        self.gridLayout_4.addWidget(self.pushButton_smooth_change_laser_red_1_stop, 13, 4, 1, 4)
        self.doubleSpinBox_lock_red_1_beta = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_lock_red_1_beta.setFont(font)
        self.doubleSpinBox_lock_red_1_beta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_lock_red_1_beta.setMaximum(999999.0)
        self.doubleSpinBox_lock_red_1_beta.setSingleStep(0.01)
        self.doubleSpinBox_lock_red_1_beta.setProperty("value", 0.0)
        self.doubleSpinBox_lock_red_1_beta.setObjectName("doubleSpinBox_lock_red_1_beta")
        self.gridLayout_4.addWidget(self.doubleSpinBox_lock_red_1_beta, 8, 7, 1, 1)
        self.doubleSpinBox_nu_red_1_smooth_delta_t = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_nu_red_1_smooth_delta_t.setFont(font)
        self.doubleSpinBox_nu_red_1_smooth_delta_t.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_nu_red_1_smooth_delta_t.setDecimals(1)
        self.doubleSpinBox_nu_red_1_smooth_delta_t.setMaximum(300.0)
        self.doubleSpinBox_nu_red_1_smooth_delta_t.setSingleStep(0.1)
        self.doubleSpinBox_nu_red_1_smooth_delta_t.setProperty("value", 10.0)
        self.doubleSpinBox_nu_red_1_smooth_delta_t.setObjectName("doubleSpinBox_nu_red_1_smooth_delta_t")
        self.gridLayout_4.addWidget(self.doubleSpinBox_nu_red_1_smooth_delta_t, 12, 4, 1, 4)
        self.pushButton_lock_laser_red_1_off = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_lock_laser_red_1_off.setFont(font)
        self.pushButton_lock_laser_red_1_off.setObjectName("pushButton_lock_laser_red_1_off")
        self.gridLayout_4.addWidget(self.pushButton_lock_laser_red_1_off, 9, 4, 1, 4)
        self.doubleSpinBox_nu_red_1_want = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_nu_red_1_want.setFont(font)
        self.doubleSpinBox_nu_red_1_want.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_nu_red_1_want.setDecimals(6)
        self.doubleSpinBox_nu_red_1_want.setMinimum(345.5)
        self.doubleSpinBox_nu_red_1_want.setMaximum(346.5)
        self.doubleSpinBox_nu_red_1_want.setSingleStep(1e-06)
        self.doubleSpinBox_nu_red_1_want.setProperty("value", 346.00022)
        self.doubleSpinBox_nu_red_1_want.setObjectName("doubleSpinBox_nu_red_1_want")
        self.gridLayout_4.addWidget(self.doubleSpinBox_nu_red_1_want, 6, 4, 1, 4)
        self.line_11 = QtWidgets.QFrame(self.groupBox_3)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_4.addWidget(self.line_11, 10, 0, 1, 8)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem48, 0, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 1, 1, 1, 2)
        self.doubleSpinBox_sawtooth_nu_blue_1_detuned = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_sawtooth_nu_blue_1_detuned.setFont(font)
        self.doubleSpinBox_sawtooth_nu_blue_1_detuned.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_sawtooth_nu_blue_1_detuned.setDecimals(6)
        self.doubleSpinBox_sawtooth_nu_blue_1_detuned.setMinimum(755.0)
        self.doubleSpinBox_sawtooth_nu_blue_1_detuned.setMaximum(755.5)
        self.doubleSpinBox_sawtooth_nu_blue_1_detuned.setSingleStep(1e-06)
        self.doubleSpinBox_sawtooth_nu_blue_1_detuned.setProperty("value", 755.18665)
        self.doubleSpinBox_sawtooth_nu_blue_1_detuned.setObjectName("doubleSpinBox_sawtooth_nu_blue_1_detuned")
        self.gridLayout_7.addWidget(self.doubleSpinBox_sawtooth_nu_blue_1_detuned, 2, 3, 1, 2)
        self.doubleSpinBox_sawtooth_nu_blue_1_init = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_sawtooth_nu_blue_1_init.setFont(font)
        self.doubleSpinBox_sawtooth_nu_blue_1_init.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_sawtooth_nu_blue_1_init.setDecimals(6)
        self.doubleSpinBox_sawtooth_nu_blue_1_init.setMinimum(755.0)
        self.doubleSpinBox_sawtooth_nu_blue_1_init.setMaximum(755.5)
        self.doubleSpinBox_sawtooth_nu_blue_1_init.setSingleStep(1e-06)
        self.doubleSpinBox_sawtooth_nu_blue_1_init.setProperty("value", 755.18677)
        self.doubleSpinBox_sawtooth_nu_blue_1_init.setObjectName("doubleSpinBox_sawtooth_nu_blue_1_init")
        self.gridLayout_7.addWidget(self.doubleSpinBox_sawtooth_nu_blue_1_init, 1, 3, 1, 2)
        self.doubleSpinBox_sawtooth_delta_t1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_sawtooth_delta_t1.setFont(font)
        self.doubleSpinBox_sawtooth_delta_t1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_sawtooth_delta_t1.setDecimals(1)
        self.doubleSpinBox_sawtooth_delta_t1.setMaximum(100.0)
        self.doubleSpinBox_sawtooth_delta_t1.setSingleStep(0.1)
        self.doubleSpinBox_sawtooth_delta_t1.setProperty("value", 10.0)
        self.doubleSpinBox_sawtooth_delta_t1.setObjectName("doubleSpinBox_sawtooth_delta_t1")
        self.gridLayout_7.addWidget(self.doubleSpinBox_sawtooth_delta_t1, 5, 3, 1, 2)
        self.doubleSpinBox_sawtooth_delta_t2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_sawtooth_delta_t2.setFont(font)
        self.doubleSpinBox_sawtooth_delta_t2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_sawtooth_delta_t2.setDecimals(1)
        self.doubleSpinBox_sawtooth_delta_t2.setSingleStep(0.1)
        self.doubleSpinBox_sawtooth_delta_t2.setProperty("value", 2.0)
        self.doubleSpinBox_sawtooth_delta_t2.setObjectName("doubleSpinBox_sawtooth_delta_t2")
        self.gridLayout_7.addWidget(self.doubleSpinBox_sawtooth_delta_t2, 6, 3, 1, 2)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem49, 0, 2, 1, 1)
        spacerItem50 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem50, 9, 0, 1, 1)
        self.spinBox_sawtooth_total_reps = QtWidgets.QSpinBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spinBox_sawtooth_total_reps.setFont(font)
        self.spinBox_sawtooth_total_reps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_sawtooth_total_reps.setProperty("value", 1)
        self.spinBox_sawtooth_total_reps.setObjectName("spinBox_sawtooth_total_reps")
        self.gridLayout_7.addWidget(self.spinBox_sawtooth_total_reps, 7, 3, 1, 2)
        self.pushButton_sawtooth_laser_blue_1_and_2_stop = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_sawtooth_laser_blue_1_and_2_stop.setFont(font)
        self.pushButton_sawtooth_laser_blue_1_and_2_stop.setObjectName("pushButton_sawtooth_laser_blue_1_and_2_stop")
        self.gridLayout_7.addWidget(self.pushButton_sawtooth_laser_blue_1_and_2_stop, 8, 3, 1, 2)
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 7, 1, 1, 1)
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem51, 0, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 6, 1, 1, 2)
        self.pushButton_sawtooth_laser_blue_1_and_2_start = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_sawtooth_laser_blue_1_and_2_start.setFont(font)
        self.pushButton_sawtooth_laser_blue_1_and_2_start.setObjectName("pushButton_sawtooth_laser_blue_1_and_2_start")
        self.gridLayout_7.addWidget(self.pushButton_sawtooth_laser_blue_1_and_2_start, 8, 1, 1, 2)
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 5, 1, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 2, 1, 1, 2)
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem52, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 3, 1, 1, 2)
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 4, 1, 1, 2)
        self.doubleSpinBox_sawtooth_nu_blue_2_init = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_sawtooth_nu_blue_2_init.setFont(font)
        self.doubleSpinBox_sawtooth_nu_blue_2_init.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_sawtooth_nu_blue_2_init.setDecimals(6)
        self.doubleSpinBox_sawtooth_nu_blue_2_init.setMinimum(755.0)
        self.doubleSpinBox_sawtooth_nu_blue_2_init.setMaximum(755.5)
        self.doubleSpinBox_sawtooth_nu_blue_2_init.setSingleStep(1e-06)
        self.doubleSpinBox_sawtooth_nu_blue_2_init.setProperty("value", 755.25811)
        self.doubleSpinBox_sawtooth_nu_blue_2_init.setObjectName("doubleSpinBox_sawtooth_nu_blue_2_init")
        self.gridLayout_7.addWidget(self.doubleSpinBox_sawtooth_nu_blue_2_init, 3, 3, 1, 2)
        self.doubleSpinBox_sawtooth_nu_blue_2_detuned = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_sawtooth_nu_blue_2_detuned.setFont(font)
        self.doubleSpinBox_sawtooth_nu_blue_2_detuned.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_sawtooth_nu_blue_2_detuned.setDecimals(6)
        self.doubleSpinBox_sawtooth_nu_blue_2_detuned.setMinimum(755.0)
        self.doubleSpinBox_sawtooth_nu_blue_2_detuned.setMaximum(755.5)
        self.doubleSpinBox_sawtooth_nu_blue_2_detuned.setSingleStep(1e-06)
        self.doubleSpinBox_sawtooth_nu_blue_2_detuned.setProperty("value", 755.25799)
        self.doubleSpinBox_sawtooth_nu_blue_2_detuned.setObjectName("doubleSpinBox_sawtooth_nu_blue_2_detuned")
        self.gridLayout_7.addWidget(self.doubleSpinBox_sawtooth_nu_blue_2_detuned, 4, 3, 1, 2)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        self.gridLayout_6.addWidget(self.groupBox_5, 1, 2, 1, 1)
        self.verticalLayout_sawtooth_blue_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_sawtooth_blue_1.setSpacing(6)
        self.verticalLayout_sawtooth_blue_1.setObjectName("verticalLayout_sawtooth_blue_1")
        self.gridLayout_6.addLayout(self.verticalLayout_sawtooth_blue_1, 1, 0, 1, 1)
        spacerItem53 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem53, 0, 0, 1, 1)
        spacerItem54 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem54, 0, 2, 1, 1)
        spacerItem55 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem55, 1, 1, 1, 1)
        spacerItem56 = QtWidgets.QSpacerItem(1, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem56, 2, 1, 1, 1)
        self.verticalLayout_sawtooth_blue_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_sawtooth_blue_2.setSpacing(6)
        self.verticalLayout_sawtooth_blue_2.setObjectName("verticalLayout_sawtooth_blue_2")
        self.gridLayout_6.addLayout(self.verticalLayout_sawtooth_blue_2, 2, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_debug = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_debug.setObjectName("pushButton_debug")
        self.gridLayout_8.addWidget(self.pushButton_debug, 0, 0, 1, 1)
        self.spinBox_debug = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_debug.setMaximum(9999)
        self.spinBox_debug.setObjectName("spinBox_debug")
        self.gridLayout_8.addWidget(self.spinBox_debug, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_8, 2, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_6)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        XCon_Imperial.setCentralWidget(self.centralWidget)

        self.retranslateUi(XCon_Imperial)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(XCon_Imperial)

    def retranslateUi(self, XCon_Imperial):
        _translate = QtCore.QCoreApplication.translate
        XCon_Imperial.setWindowTitle(_translate("XCon_Imperial", "XCon_Imperial"))
        self.groupBox.setTitle(_translate("XCon_Imperial", "Laser Blue 1"))
        self.label_3.setText(_translate("XCon_Imperial", " nu_blue_1_want [THz]:"))
        self.label_2.setText(_translate("XCon_Imperial", " lock_blue_1_alpha:"))
        self.pushButton_lock_laser_blue_1_on.setText(_translate("XCon_Imperial", "Lock ON"))
        self.pushButton_lock_laser_blue_1_off.setText(_translate("XCon_Imperial", "Lock OFF"))
        self.label.setText(_translate("XCon_Imperial", " nu_blue_1_is [THz]:"))
        self.pushButton_smooth_change_laser_blue_1_start.setText(_translate("XCon_Imperial", "Smooth detuning START"))
        self.label_5.setText(_translate("XCon_Imperial", " nu_blue_1_smooth_want [THz]:"))
        self.pushButton_smooth_change_laser_blue_1_stop.setText(_translate("XCon_Imperial", "Smooth detuning STOP"))
        self.label_6.setText(_translate("XCon_Imperial", " nu_blue_1_smooth_delta_t [s]:"))
        self.label_4.setText(_translate("XCon_Imperial", " lock_blue_1_beta:"))
        self.label_nu_blue_1_is.setText(_translate("XCon_Imperial", "0.0"))
        self.label_7.setText(_translate("XCon_Imperial", " Lock is "))
        self.label_lock_blue_1_status.setText(_translate("XCon_Imperial", "OFF"))
        self.groupBox_4.setTitle(_translate("XCon_Imperial", "Laser Red 2"))
        self.pushButton_smooth_change_laser_red_2_stop.setText(_translate("XCon_Imperial", "Smooth detuning STOP"))
        self.label_30.setText(_translate("XCon_Imperial", " nu_red_2_smooth_delta_t [s]:"))
        self.label_27.setText(_translate("XCon_Imperial", " lock_red_2_alpha:"))
        self.pushButton_smooth_change_laser_red_2_start.setText(_translate("XCon_Imperial", "Smooth detuning START"))
        self.pushButton_lock_laser_red_2_on.setText(_translate("XCon_Imperial", "Lock ON"))
        self.label_29.setText(_translate("XCon_Imperial", " nu_red_2_smooth_want [THz]:"))
        self.label_28.setText(_translate("XCon_Imperial", " lock_red_2_beta:"))
        self.pushButton_lock_laser_red_2_off.setText(_translate("XCon_Imperial", "Lock OFF"))
        self.label_26.setText(_translate("XCon_Imperial", " nu_red_2_want [THz]:"))
        self.label_24.setText(_translate("XCon_Imperial", " nu_red_2_is [THz]:"))
        self.label_22.setText(_translate("XCon_Imperial", " Lock is "))
        self.label_nu_red_2_is.setText(_translate("XCon_Imperial", "0.0"))
        self.label_lock_red_2_status.setText(_translate("XCon_Imperial", "OFF"))
        self.groupBox_2.setTitle(_translate("XCon_Imperial", "Laser Blue 2"))
        self.pushButton_lock_laser_blue_2_on.setText(_translate("XCon_Imperial", "Lock ON"))
        self.label_16.setText(_translate("XCon_Imperial", " lock_blue_2_beta:"))
        self.label_9.setText(_translate("XCon_Imperial", " nu_blue_2_want [THz]:"))
        self.pushButton_smooth_change_laser_blue_2_start.setText(_translate("XCon_Imperial", "Smooth detuning START"))
        self.label_lock_blue_2_status.setText(_translate("XCon_Imperial", "OFF"))
        self.label_14.setText(_translate("XCon_Imperial", " nu_blue_2_is [THz]:"))
        self.pushButton_smooth_change_laser_blue_2_stop.setText(_translate("XCon_Imperial", "Smooth detuning STOP"))
        self.label_8.setText(_translate("XCon_Imperial", " lock_blue_2_alpha:"))
        self.label_nu_blue_2_is.setText(_translate("XCon_Imperial", "0.0"))
        self.label_11.setText(_translate("XCon_Imperial", " nu_blue_2_smooth_delta_t [s]:"))
        self.label_10.setText(_translate("XCon_Imperial", " nu_blue_2_smooth_want [THz]:"))
        self.pushButton_lock_laser_blue_2_off.setText(_translate("XCon_Imperial", "Lock OFF"))
        self.label_12.setText(_translate("XCon_Imperial", " Lock is "))
        self.groupBox_3.setTitle(_translate("XCon_Imperial", "Laser Red 1"))
        self.label_19.setText(_translate("XCon_Imperial", " nu_red_1_smooth_want [THz]:"))
        self.label_13.setText(_translate("XCon_Imperial", " Lock is "))
        self.label_15.setText(_translate("XCon_Imperial", " nu_red_1_want [THz]:"))
        self.pushButton_lock_laser_red_1_on.setText(_translate("XCon_Imperial", "Lock ON"))
        self.label_18.setText(_translate("XCon_Imperial", " lock_red_1_alpha:"))
        self.label_20.setText(_translate("XCon_Imperial", " nu_red_1_smooth_delta_t [s]:"))
        self.label_17.setText(_translate("XCon_Imperial", " nu_red_1_is [THz]:"))
        self.label_nu_red_1_is.setText(_translate("XCon_Imperial", "0.0"))
        self.label_lock_red_1_status.setText(_translate("XCon_Imperial", "OFF"))
        self.pushButton_smooth_change_laser_red_1_start.setText(_translate("XCon_Imperial", "Smooth detuning START"))
        self.label_21.setText(_translate("XCon_Imperial", " lock_red_1_beta:"))
        self.pushButton_smooth_change_laser_red_1_stop.setText(_translate("XCon_Imperial", "Smooth detuning STOP"))
        self.pushButton_lock_laser_red_1_off.setText(_translate("XCon_Imperial", "Lock OFF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("XCon_Imperial", "red and blue lasers"))
        self.groupBox_5.setTitle(_translate("XCon_Imperial", "Sawtooth detuning blue lasers"))
        self.label_23.setText(_translate("XCon_Imperial", " nu_blue_1_init [THz]:"))
        self.pushButton_sawtooth_laser_blue_1_and_2_stop.setText(_translate("XCon_Imperial", "STOP"))
        self.label_33.setText(_translate("XCon_Imperial", " total_reps:"))
        self.label_32.setText(_translate("XCon_Imperial", " delta_t2 [s]:"))
        self.pushButton_sawtooth_laser_blue_1_and_2_start.setText(_translate("XCon_Imperial", "START"))
        self.label_31.setText(_translate("XCon_Imperial", " delta_t1 [s]:"))
        self.label_25.setText(_translate("XCon_Imperial", " nu_blue_1_detuned [THz]:"))
        self.label_34.setText(_translate("XCon_Imperial", " nu_blue_2_init [THz]:"))
        self.label_35.setText(_translate("XCon_Imperial", " nu_blue_2_detuned [THz]:"))
        self.pushButton_debug.setText(_translate("XCon_Imperial", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("XCon_Imperial", "functions: SAWTOOTH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    XCon_Imperial = QtWidgets.QMainWindow()
    ui = Ui_XCon_Imperial()
    ui.setupUi(XCon_Imperial)
    XCon_Imperial.show()
    sys.exit(app.exec_())

